### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by ofirkris** [mprzewie/dmfa_inpainting#2]
Hello, thanks for adding training code - can you also share weights for CelebA and Places2?

**Comment by mprzewie** [comment]
Hi @ofirkris, thank you for your interest in our work! 
Sorry for a few days delay, but I've added a link to Google Drive with weights of multiple DMFA models in the README, including one trained on both complete and incomplete 64x64 pixel CelebA images. Check out the `Weights` section, I hope it'll be helpful! 

We don't have weights for Places2, as we never trained our model on this dataset. However, it could be interesting to try it out. If you do that, do let me know :)

Here is a brief example of how you can load the model (assuming you are in the main repo directory):

```python
from pathlib import Path
import json
from scripts.common import dmfa_from_args
from dotted.utils import dot
import torch

dmfa_path = Path(...) # path to a directory with saved DMFA
with (dmfa_path / "args.json").open("r") as f:        
    dmfa_args = dot(json.load(f))
inpainter = common_loaders.dmfa_from_args(dmfa_args)
checkpoint = torch.load((dmfa_path / "training.state"), map_location="cpu")    
inpainter.load_state_dict(checkpoint["inpainter"])
```
